domains:
  '*': 'http://localhost:4200|POST,PATCH,ADD,GET,PUT,DELETE,OPTIONS|Authorization,X-CSRF-Token,Content-type,Cache-Control|true'
_core:
  default_config_hash: nCJuMn5x07t9O5N-iSHrh4M1-cEN43AOdMu32YtvYbc
