link_domain: null
bc_entity_resource_permissions: false
_core:
  default_config_hash: bwcdqlollZ-bMAg90HtLMFFBgY7UXJohIln7BICIooE
resources:
  'entity:user':
    GET:
      supported_formats:
        - json
      supported_auth:
        - cookie
    POST:
      supported_formats:
        - json
      supported_auth:
        - cookie
    DELETE:
      supported_formats:
        - json
      supported_auth:
        - cookie
  'entity:node':
    GET:
      supported_formats:
        - api_json
        - json
      supported_auth:
        - cookie
    POST:
      supported_formats:
        - api_json
        - json
      supported_auth:
        - cookie
    DELETE:
      supported_formats:
        - api_json
        - json
      supported_auth:
        - cookie